export const ACTION_CATEGORIES_START_LOADING = 'ACTION_CATEGORIES_START_LOADING';
export const ACTION_FETCH_CATEGORIES_SUCCESS = 'ACTION_FETCH_CATEGORIES_SUCCESS';
export const ACTION_FETCH_CATEGORIES_ERROR = 'ACTION_FETCH_CATEGORIES_ERROR';
