export const ACTION_ADD_EDIT_EVENT_START_LOADING = 'ACTION_ADD_EDIT_EVENT_START_LOADING';
export const ACTION_FETCH_EVENT_TO_EDIT_SUCCESS = 'ACTION_FETCH_EVENT_TO_EDIT_SUCCESS';
export const ACTION_FETCH_EVENT_TO_EDIT_ERROR = 'ACTION_FETCH_EVENT_TO_EDIT_ERROR';
export const ADD_EDIT_EVENT_SUCCESS = 'ADD_EDIT_EVENT_SUCCESS';
export const ADD_EDIT_EVENT_ERROR = 'ADD_EDIT_EVENT_ERROR';
