export const ACTION_EVENTS_START_LOADING = 'ACTION_EVENTS_START_LOADING';
export const ACTION_FETCH_EVENTS_SUCCESS = 'ACTION_FETCH_EVENTS_SUCCESS';
export const ACTION_FETCH_EVENTS_ERROR = 'ACTION_FETCH_EVENTS_ERROR';
export const ACTION_FETCH_FILTERED_EVENTS_SUCCESS = 'ACTION_FETCH_FILTERED_EVENTS_SUCCESS';
export const ACTION_FETCH_FILTERED_EVENTS_ERROR = 'ACTION_FETCH_FILTERED_EVENTS_ERROR';
