export const ACTION_AUTH_START_LOADING = 'ACTION_AUTH_START_LOADING';
export const ACTION_CHANGE_ACTIVE_AUTH_TYPE = 'ACTION_CHANGE_ACTIVE_AUTH_TYPE';
export const ACTION_CHANGE_NOTIFICATION_STATUS = 'ACTION_CHANGE_NOTIFICATION_STATUS';
export const ACTION_AUTHENTICATE_SUCCESS = 'ACTION_AUTHENTICATE_SUCCESS';
export const ACTION_AUTHENTICATE_ERROR = 'ACTION_AUTHENTICATE_ERROR';
export const ACTION_SIGN_OUT_SUCCESS = 'ACTION_SIGN_OUT_SUCCESS';
export const ACTION_SIGN_OUT_ERROR = 'ACTION_SIGN_OUT_ERROR';
