version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Setup Server Dependencies and Run Tests
          command: |
            cd server
            npm install
            npm test
      - run:
          name: Setup Client Dependencies and Run Tests
          command: |
            cd client
            npm install
            npm test
            npm run build
  deploy:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to EC2
          command: aws deploy list-applications
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master