version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Setup Server Dependencies and Run Tests
          command: |
            cd server
            npm install
            npm test
      - run:
          name: Setup Client Dependencies and Run Tests
          command: |
            cd client
            npm install
            npm test