version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Setup Server Dependencies
          command: |
            cd server
            npm install
      - run:
          name: Setup Client Dependencies
          command: |
            cd client
            npm install